//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace u23668475_HW03.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChartArchive
    {
        public int ChartID { get; set; }
        public string FileName { get; set; }
        public string FileType { get; set; }
        public byte[] ChartData { get; set; }
    }
}
